config/routes.rb
Rails.application.routes.draw do
  resources :cards

end

app/models/card.rb
class Card < ActiveRecord::Base
  has_many :scores
  validates :tag, :name, :card_type, :rarity, :cost, presence: true
  validates :tag, :name, uniqueness: true
end

app/models/score.rb
class Score < ActiveRecord::Base
  belongs_to :card
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  # GET /cards
  # GET /cards.json
  def index
    respond_to do |format|
      @valid_cards = @cards = Card.all.to_a
      format.html{
        @num_cards = @valid_cards.size
      }
      format.js{
        if params[:search]
          @valid_cards = @cards.delete_if {|card| !(card.name.include? params[:search])}
        end
        if params[:player_class]
          @valid_cards = @cards.delete_if {|card| !card.player_class.nil? and !(card.player_class.eql? params[:player_class])}
        else
          puts "WTF Card Controller"
        end
    
        @num_cards = @valid_cards.size
        if params[:page_index]
          @valid_cards = @valid_cards.slice((params[:page_index].to_i-1)*8,8)
        end
      }
    end   
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use cal
  # lbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.require(:card).permit(:tag, :name, :card_type, :rarity, :cost, :attack, :health, :player_class)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
  
  def rarities
    ['Common', 'Rare', 'Epic', 'Legendary']
  end

  def player_classes
    ['Druid', 'Hunter', 'Mage', 'Paladin', 'Priest', 'Rogue', 'Shaman', 'Warlock', 'Warrior']
  end
  
  def player_class_colour player_class
    colours = {}
    colours['Druid'] = "#a5754a"
    colours['Hunter'] = "#429242"
    colours['Mage'] = "#929bbe"
    colours['Paladin'] = "#e7be4a"
    colours['Priest'] = "#e7ebef"
    colours['Rogue'] = "#3c3334"
    colours['Shaman'] = "#5259a5"
    colours['Warlock'] = "#8a6097"
    colours['Warrior'] = "#953331"
    colours[player_class]
  end

  def player_class_complementary_colour player_class
    colours = {}
    colours['Druid'] = "#f1cfb0"
    colours['Hunter'] = "#9fd19f"
    colours['Mage'] = "#e7e9f2"
    colours['Paladin'] = "#ffe69e"
    colours['Priest'] = "#ffffff"
    colours['Rogue'] = "#a28d90"
    colours['Shaman'] = "#a9acdd"
    colours['Warlock'] = "#d2bfd8"
    colours['Warrior'] = "#df8b89"
    colours[player_class]
  end

  def image_dir
    "https://raw.githubusercontent.com/bertvernboyd/hearthstone/master/lib/assets/images/"
  end
end

app/views/cards/_form.html.erb
<%= form_for(@card) do |f| %>
  <% if @card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% @card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tag %><br>
    <%= f.text_field :tag %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :card_type %><br>
    <%= f.text_field :card_type %>
  </div>
  <div class="field">
    <%= f.label :rarity %><br>
    <%= f.text_field :rarity %>
  </div>
  <div class="field">
    <%= f.label :cost %><br>
    <%= f.number_field :cost %>
  </div>
  <div class="field">
    <%= f.label :attack %><br>
    <%= f.number_field :attack %>
  </div>
  <div class="field">
    <%= f.label :health %><br>
    <%= f.number_field :health %>
  </div>
  <div class="field">
    <%= f.label :player_class %><br>
    <%= f.text_field :player_class %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<h1>Editing card</h1>

<%= render 'form' %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<%= form_tag({action: :index}, remote: true, method: 'get') do %>


  <%= submit_tag 'submit', id: "submit" %>
  <%= hidden_field_tag 'page_index', '1' %>
  <%= hidden_field_tag 'player_class', 'Druid' %>

  <%url="https://raw.githubusercontent.com/bertvernboyd/hearthstone/master/lib/assets/images/icons/"%>

  <div class="section group" id="header">
    <div class="col span_1_of_3">
      <%= text_field_tag 'search'%>
    </div>
    <div class="col span_1_of_3">
      Mechanics
    </div>
    <div class="col span_1_of_3">
      <div class "section group">
        <% rarities.each do |rarity|%>
          <div class="col span_1_of_5">
             <img src="<%=url+rarity.downcase%>.png"> 
          </div>
        <% end %>
        <div class="col span_1_of_5">
             <img src="<%=url%>all.png">
        </div>
      </div>    
    </div>
  </div>

  <div>
    <div class="col_left">
      <%= submit_tag nil, id: "page_left" %>
    </div>
    <div class="col_right">
      <%= submit_tag nil, id: "page_right" %>
    </div>
    <div class="col_center">
      <div class="section group" id="icons">
  
        <% player_classes.each do |player_class|%>

          <div class="col span_1_of_<%=player_classes.size %> icon" id="<%=player_class%>">
            <img src="<%=url+player_class%>_61x49.png">
          </div>
        <% end %>

      </div>
      <div>
        <% c = 4 %>
        <% r = 2 %>
        <% r.times do |i| %>
          <div class="section group">
            <% for j in 0...c %>
              <div class="col span_1_of_<%=c%> relative">
                <img id="card_img_<%=j+c*i%>"/>
                <div id="score_<%=j+c*i%>" class="absolute circle"></div>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/cards/index.js.erb
var gray = "#777777";
var red = "#7F0000";

<%url=image_dir+"icons/"%>


if($._data($(".col_left").get(0), "events")){}
else if($('#page_index').data('page_index') != 1)
{
  $('.col_left').css("background-color",red);
  $('.col_left').on("click",function(){
    $('#page_index').data('page_index', $('#page_index').data('page_index') - 1);
    $('#page_index').val($('#page_index').data('page_index'));
    $('#submit').click();
  });
}
if($('#page_index').data('page_index') == 1)
{
  $('.col_left').off("click");
  $('.col_left').css("background-color",gray);
}

var max_page = Math.ceil(<%= @num_cards %> / 8);
if($._data($(".col_right").get(0), "events")){}
else if($('#page_index').data('page_index') != max_page)
{
  $('.col_right').css("background-color",red);
  $('.col_right').on("click",function(){
    $('#page_index').data('page_index', $('#page_index').data('page_index') + 1);
    $('#page_index').val($('#page_index').data('page_index'));
    $('#submit').click();
  });
}
if($('#page_index').data('page_index') == max_page)
{
  $('.col_right').off("click");
  $('.col_right').css("background-color","gray");
}


<% player_classes.each do |player_class|%>
  $("#<%=player_class%>").find("img").removeAttr("src")
  if($("#player_class").val() == "<%= player_class %>")
  {
    $("#<%=player_class%>").find("img").attr("src", "<%=url+player_class.downcase%>_61x49.png")
    $('.col_center').css("background-color","<%=player_class_colour player_class %>");
    $('.absolute').css("background-color", "<%=player_class_complementary_colour player_class %>");
  }
  else
  {
    $("#<%=player_class%>").find("img").attr("src", "<%=url%>bw_<%=player_class.downcase%>_61x49.png")
  }
<% end %>



<% index = 0%>
var id;

<% for i in 0..7 %>
  id = "#card_img_<%=i%>";
  $(id).removeAttr("src");
  score = "#score_<%=i%>";
  $(score).text("");
<% end %>

<% @valid_cards.slice(0,8).each do |card| %>
  id = "#card_img_<%=index%>";
  img_src = "<%=image_dir+card.tag %>.png"
  score = "#score_<%=index%>";
  $(score).text(<%=card.scores.where(player_class: params[:player_class]).first.value%>);
  <% index += 1 %>
  $(id).attr("src", img_src);

<% end %>

app/views/cards/new.html.erb
<h1>New card</h1>

<%= render 'form' %>

<%= link_to 'Back', cards_path %>

app/views/cards/show.html.erb
<p id="notice"><%= notice %></p>

<img src="https://raw.githubusercontent.com/bertvernboyd/hearthstone/master/lib/assets/images/<%=@card.tag%>.png">

<br>

<%= link_to 'Back', cards_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hearthstone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>